### ISSUE TITLE
is `set_linger()` working?

### ISSUE THREAD

**Issue by dmichiels** [thehydroimpulse/nanomsg.rs#137]
Hello,
I'm trying to use Nanomsg and Rust, but I have a problem when I use `set_linger()`.

Here is an example that doesn't work for me : 
```
extern crate nanomsg;

use nanomsg::{Socket, Protocol};
use std::thread;

fn main() {

    let srv = thread::spawn(move || {
        let mut s = Socket::new(Protocol::Pull).unwrap();
        s.bind(&"inproc://test").unwrap();

        thread::sleep_ms(2000);

        let r = &mut s as &mut ::std::io::Read;

        let mut msg = String::new();
        r.read_to_string(&mut msg).unwrap();
        println!("msg : {}", msg);
    });

    // let the server start
    thread::sleep_ms(100);

    let mut s = Socket::new(Protocol::Push).unwrap();
    let mut ep = s.connect(&"inproc://test").unwrap();
    s.set_linger(-1).expect("cannot set linger");
    s.nb_write(&format!("hello nanomsg").as_bytes()).unwrap();
    println!("Send the msg");
    ep.shutdown().expect("cannot shutdown");

    srv.join();
}
```

I need it because I want to disconnect and reconnect to another address, but without loosing the IPs that are "pending".

Have I misunderstood the linger, or is this a bug?

Thank you in advance, 
Denis

**Comment by sjmackenzie** [comment]
IP = (Flow Based Programming) Information Packet not IP address :-)

**Comment by blabaere** [comment]
@dmichiels @sjmackenzie First of all you have to know that from the words of the current nanomsg maintainer, the inproc transport still has a few bugs, even if it is improving. Feel free to check the [mailing list archive](http://www.freelists.org/archive/nanomsg/) regarding this.
Then, in your example you are using the non-blocking send function ```nb_write```, but the sleep calls ensure that the ```recv``` always occurs after the ```send```, which should return an EAGAIN error in this case (bug in inproc I say). Using a TCP transport, it fails as expected, and then using ```write_all``` instead of ```nb_write``` works properly.

So my guess is that it could be a bug or a limitation of the inproc transport. 
To sum up :
 - Don't use ```nb_write``` without checking the result, and don't use it at all when you know for sure the server is not receiving.
 - If you really need this to work with inproc, contact the maintainer via the [mailing list](http://nanomsg.org/community.html), or [gitter](https://gitter.im/nanomsg/nanomsg).
 - If you can switch to TCP, it will work fine.

PS : you'll find a more up-to-date fork of [nanomsg.rs there](https://github.com/blabaere/nanomsg.rs).

Here is the fixed example:
```rust
extern crate nanomsg;

use nanomsg::{Socket, Protocol};
use std::thread;

use std::io::{Read, Write};

fn main() {

    let srv = thread::spawn(move || {
        println!("server: create socket");
        let mut s = Socket::new(Protocol::Pull).unwrap();
        println!("server: bind socket");
        //s.bind(&"inproc://test").unwrap();
        s.bind(&"tcp://127.0.0.1:5456").unwrap();

        println!("server: sleep 500");
        thread::sleep_ms(500);

        let mut msg = String::new();
        println!("server: recv");
        s.read_to_string(&mut msg).unwrap();
        println!("server: msg: {}", msg);
    });

    println!("client: sleep 100");
    // let the server start
    thread::sleep_ms(100);

    println!("client: create socket");
    let mut s = Socket::new(Protocol::Push).unwrap();
    println!("client: connect socket");
    //let mut ep = s.connect(&"inproc://test").unwrap();
    let mut ep = s.connect(&"tcp://127.0.0.1:5456").unwrap();
    println!("client: set_linger");
    s.set_linger(-1).expect("cannot set linger");
    println!("client: write_all");
    s.write_all("hello nanomsg".as_bytes()).unwrap();
    println!("client: shutdown");
    ep.shutdown().expect("cannot shutdown");
    println!("client: wait server");

    srv.join();
}
```

Regards,
Benoît

**Comment by dmichiels** [comment]
Thank you a lot for this great response.
It fix my problem (move to tcp) and learn me about Nanomsg!

**Comment by sjmackenzie** [comment]
+1 thanks Benoît, that was helpful.
